#include "thirdparty/opengr2/libopengrn/compression.h"
#include "thirdparty/opengr2/libopengrn/crc.h"
#include "thirdparty/opengr2/libopengrn/darray.h"
#include "thirdparty/opengr2/libopengrn/debug.h"
#include "thirdparty/opengr2/libopengrn/dllapi.h"
#include "thirdparty/opengr2/libopengrn/elements.h"
// #include "thirdparty/opengr2/libopengrn/gr2.h"
#include "thirdparty/opengr2/libopengrn/magic.h"
#include "thirdparty/opengr2/libopengrn/oodle1.h"
#include "thirdparty/opengr2/libopengrn/platform.h"
#include "thirdparty/opengr2/libopengrn/structures.h"
#include "thirdparty/opengr2/libopengrn/typeinfo.h"
//#include "thirdparty/opengr2/libopengrn/virtual_ptr.h"
